import { Graph, StateGraph,StateSchema,type GraphNode,START,END } from "@langchain/langgraph";
import z from "zod"
import { mistralModel, cohereModel, geminiModel } from "./model.ai.js";
import { createAgent, HumanMessage, providerStrategy,toolStrategy } from "langchain";
import { start } from "node:repl";
// NOte -= Agar gemnin model use to create agent te we can use Provider Strategy but but but if we want to use another model to create an Agent hen we haveto use toolStrategy 



//  state Schema is used to define format of data so thaat between node we can communicate iin proper do format 

// state is use to define data jo flow hoga and bueprint schema define karat hai 


    const state = new StateSchema({
        problem: z.string().default(""),
        solution_1: z.string().default(""),
        solution_2: z.string().default(""),
        judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default("")
})
    }) 

    const solutionNode: GraphNode<typeof state>=async (state)=>{
        const [ mistalResponse , CohereResponse ] = await Promise.all(
            [
                mistralModel.invoke(state.problem),
                cohereModel.invoke(state.problem)
            ]
        )

        return {
            solution_1 : mistalResponse.text,
            solution_2 : CohereResponse.text
        }
    }
    

    const judgeNode: GraphNode<typeof state> = async(state )=>{

        const {problem,solution_1,solution_2} = state

        const judge =  createAgent({
            model:mistralModel,
            responseFormat: toolStrategy(z.object({
                solution_1_score : z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(120),
                solution_1_reasoning: z.string(),
                solution_2_reasoning : z.string()
            })),systemPrompt:"You ar Jude tasked with evaluating two solutions generated by diffrent AI models. please provide a score out of 10 for each solution , along with reasoning of score"
        })

        const judgeResponse = await judge.invoke({
            messages:[
                new HumanMessage(`
                    Problem : ${problem}
                    solution 1 : ${solution_1}
                    solution 2 : ${solution_2}
                    please Evaluate The solutions and provide score of reasoning         
                    `)
            ]


        })

        const { solution_1_score,solution_2_score,solution_1_reasoning,solution_2_reasoning} = judgeResponse.structuredResponse

        return {
            judge : {
                solution_1_score,
                solution_2_score,
                solution_1_reasoning,
                solution_2_reasoning
            
            }
        }

    }
    //  now idhaar we have to create agent as we want to get data in proper format 

    const graph = new StateGraph(state)
    .addNode("Solution",solutionNode)
    .addNode("judgeNode",judgeNode)
    // ya ha toh hamen grpah me node add kardi lekin edge ki direction bata ni baki hai woh nicha karraha hai dekho
    .addEdge(START,"Solution")
    .addEdge("Solution","judgeNode")
    .addEdge("judgeNode",END)
    .compile()

    // both Edges and Nodes Added and Grpah Created 

    
    export default async function runGraph(problem:String)
    {
        const result = await graph.invoke({
            problem: problem
        }) 
        
        return result 
        // problem sw Q invoke kyiya Donubt 
        

    }